# Generated by Django 5.2.16 on 2026-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='currency_symbol',
            field=models.CharField(blank=True, default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='footer_greeting',
            field=models.TextField(blank=True, default='Thank you for dining with us! Please visit again.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='TC-', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='paper_width',
            field=models.CharField(blank=True, default='80mm (Standard Thermal)', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
