# Generated by Django 5.2.16 on 2026-09-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurantsettings_currency_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsettings',
            name='paper_width',
        ),
    ]
