# Generated by Django 5.2.16 on 2026-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_restaurantsettings_paper_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='packing_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
