# Generated by Django 5.2.16 on 2026-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
