# Generated by Django 5.2.16 on 2026-08-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_diningtable_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('arrival_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('awaiting_guest', 'Awaiting Guest'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='awaiting_guest', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.diningtable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
