# Generated by Django 5.2.16 on 2026-08-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('billing', 'Billing'), ('cleaning', 'Cleaning')], default='available', max_length=20),
        ),
    ]
