# Generated by Django 5.2.16 on 2026-09-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_diningtable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('billing', 'Billing'), ('cleaning', 'Cleaning'), ('no_service', 'No Service'), ('inactive', 'No Service')], default='available', max_length=20),
        ),
    ]
