# Generated by Django 5.2.16 on 2026-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_diningtable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('capacity', 'Seat Capacity'), ('section', 'Dining Area')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('option_type', 'value')},
            },
        ),
    ]
