# Generated by Django 5.2.16 on 2026-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_half_price_menuitem_quarter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('diet_type', 'Diet Type'), ('spice_level', 'Spice Level')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('option_type', 'value')},
            },
        ),
    ]
