# Generated by Django 5.2.16 on 2026-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='diet_type',
            field=models.CharField(blank=True, default='Veg', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(blank=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
